/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TableIndexRouteImport } from './routes/table/index'
import { Route as ModalIndexRouteImport } from './routes/modal/index'
import { Route as DropdownIndexRouteImport } from './routes/dropdown/index'
import { Route as ButtonVariantIndexRouteImport } from './routes/button-variant/index'
import { Route as ButtonBooleanIndexRouteImport } from './routes/button-boolean/index'
import { Route as AccordionIndexRouteImport } from './routes/accordion/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TableIndexRoute = TableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModalIndexRoute = ModalIndexRouteImport.update({
  id: '/modal/',
  path: '/modal/',
  getParentRoute: () => rootRouteImport,
} as any)
const DropdownIndexRoute = DropdownIndexRouteImport.update({
  id: '/dropdown/',
  path: '/dropdown/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonVariantIndexRoute = ButtonVariantIndexRouteImport.update({
  id: '/button-variant/',
  path: '/button-variant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonBooleanIndexRoute = ButtonBooleanIndexRouteImport.update({
  id: '/button-boolean/',
  path: '/button-boolean/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccordionIndexRoute = AccordionIndexRouteImport.update({
  id: '/accordion/',
  path: '/accordion/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accordion/': typeof AccordionIndexRoute
  '/button-boolean/': typeof ButtonBooleanIndexRoute
  '/button-variant/': typeof ButtonVariantIndexRoute
  '/dropdown/': typeof DropdownIndexRoute
  '/modal/': typeof ModalIndexRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accordion': typeof AccordionIndexRoute
  '/button-boolean': typeof ButtonBooleanIndexRoute
  '/button-variant': typeof ButtonVariantIndexRoute
  '/dropdown': typeof DropdownIndexRoute
  '/modal': typeof ModalIndexRoute
  '/table': typeof TableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accordion/': typeof AccordionIndexRoute
  '/button-boolean/': typeof ButtonBooleanIndexRoute
  '/button-variant/': typeof ButtonVariantIndexRoute
  '/dropdown/': typeof DropdownIndexRoute
  '/modal/': typeof ModalIndexRoute
  '/table/': typeof TableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accordion/'
    | '/button-boolean/'
    | '/button-variant/'
    | '/dropdown/'
    | '/modal/'
    | '/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accordion'
    | '/button-boolean'
    | '/button-variant'
    | '/dropdown'
    | '/modal'
    | '/table'
  id:
    | '__root__'
    | '/'
    | '/accordion/'
    | '/button-boolean/'
    | '/button-variant/'
    | '/dropdown/'
    | '/modal/'
    | '/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccordionIndexRoute: typeof AccordionIndexRoute
  ButtonBooleanIndexRoute: typeof ButtonBooleanIndexRoute
  ButtonVariantIndexRoute: typeof ButtonVariantIndexRoute
  DropdownIndexRoute: typeof DropdownIndexRoute
  ModalIndexRoute: typeof ModalIndexRoute
  TableIndexRoute: typeof TableIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table/': {
      id: '/table/'
      path: '/table'
      fullPath: '/table/'
      preLoaderRoute: typeof TableIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modal/': {
      id: '/modal/'
      path: '/modal'
      fullPath: '/modal/'
      preLoaderRoute: typeof ModalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dropdown/': {
      id: '/dropdown/'
      path: '/dropdown'
      fullPath: '/dropdown/'
      preLoaderRoute: typeof DropdownIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-variant/': {
      id: '/button-variant/'
      path: '/button-variant'
      fullPath: '/button-variant/'
      preLoaderRoute: typeof ButtonVariantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-boolean/': {
      id: '/button-boolean/'
      path: '/button-boolean'
      fullPath: '/button-boolean/'
      preLoaderRoute: typeof ButtonBooleanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accordion/': {
      id: '/accordion/'
      path: '/accordion'
      fullPath: '/accordion/'
      preLoaderRoute: typeof AccordionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccordionIndexRoute: AccordionIndexRoute,
  ButtonBooleanIndexRoute: ButtonBooleanIndexRoute,
  ButtonVariantIndexRoute: ButtonVariantIndexRoute,
  DropdownIndexRoute: DropdownIndexRoute,
  ModalIndexRoute: ModalIndexRoute,
  TableIndexRoute: TableIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
