/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ButtonVariantIndexRouteImport } from './routes/button-variant/index'
import { Route as ButtonBooleanIndexRouteImport } from './routes/button-boolean/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonVariantIndexRoute = ButtonVariantIndexRouteImport.update({
  id: '/button-variant/',
  path: '/button-variant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ButtonBooleanIndexRoute = ButtonBooleanIndexRouteImport.update({
  id: '/button-boolean/',
  path: '/button-boolean/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/button-boolean/': typeof ButtonBooleanIndexRoute
  '/button-variant/': typeof ButtonVariantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/button-boolean': typeof ButtonBooleanIndexRoute
  '/button-variant': typeof ButtonVariantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/button-boolean/': typeof ButtonBooleanIndexRoute
  '/button-variant/': typeof ButtonVariantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/button-boolean/' | '/button-variant/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/button-boolean' | '/button-variant'
  id: '__root__' | '/' | '/button-boolean/' | '/button-variant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ButtonBooleanIndexRoute: typeof ButtonBooleanIndexRoute
  ButtonVariantIndexRoute: typeof ButtonVariantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-variant/': {
      id: '/button-variant/'
      path: '/button-variant'
      fullPath: '/button-variant/'
      preLoaderRoute: typeof ButtonVariantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/button-boolean/': {
      id: '/button-boolean/'
      path: '/button-boolean'
      fullPath: '/button-boolean/'
      preLoaderRoute: typeof ButtonBooleanIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ButtonBooleanIndexRoute: ButtonBooleanIndexRoute,
  ButtonVariantIndexRoute: ButtonVariantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
